// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 3, col: 1, offset: 18},
			expr: &actionExpr{
				pos: position{line: 3, col: 10, offset: 27},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 3, col: 10, offset: 27},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 3, col: 10, offset: 27},
							label: "v1",
							expr: &choiceExpr{
								pos: position{line: 3, col: 14, offset: 31},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 3, col: 14, offset: 31},
										name: "Object",
									},
									&zeroOrMoreExpr{
										pos: position{line: 3, col: 23, offset: 40},
										expr: &ruleRefExpr{
											pos:  position{line: 3, col: 23, offset: 40},
											name: "Field",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 3, col: 31, offset: 48},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 5, col: 1, offset: 79},
			expr: &actionExpr{
				pos: position{line: 5, col: 11, offset: 89},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 5, col: 11, offset: 89},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 5, col: 11, offset: 89},
							name: "LBRACE",
						},
						&labeledExpr{
							pos:   position{line: 5, col: 18, offset: 96},
							label: "v1",
							expr: &zeroOrMoreExpr{
								pos: position{line: 5, col: 21, offset: 99},
								expr: &ruleRefExpr{
									pos:  position{line: 5, col: 21, offset: 99},
									name: "Field",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 5, col: 28, offset: 106},
							name: "RBRACE",
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 7, col: 1, offset: 141},
			expr: &actionExpr{
				pos: position{line: 7, col: 10, offset: 150},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 7, col: 10, offset: 150},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 7, col: 10, offset: 150},
							label: "v1",
							expr: &ruleRefExpr{
								pos:  position{line: 7, col: 13, offset: 153},
								name: "Key",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 7, col: 17, offset: 157},
							name: "COLON",
						},
						&labeledExpr{
							pos:   position{line: 7, col: 23, offset: 163},
							label: "v2",
							expr: &ruleRefExpr{
								pos:  position{line: 7, col: 26, offset: 166},
								name: "Expression",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 7, col: 37, offset: 177},
							expr: &litMatcher{
								pos:        position{line: 7, col: 37, offset: 177},
								val:        ",",
								ignoreCase: false,
								want:       "\",\"",
							},
						},
					},
				},
			},
		},
		{
			name: "Key",
			pos:  position{line: 9, col: 1, offset: 213},
			expr: &choiceExpr{
				pos: position{line: 9, col: 8, offset: 220},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 9, col: 8, offset: 220},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 17, offset: 229},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 11, col: 1, offset: 241},
			expr: &choiceExpr{
				pos: position{line: 11, col: 10, offset: 250},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 11, col: 10, offset: 250},
						name: "Null",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 17, offset: 257},
						name: "Boolean",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 27, offset: 267},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 36, offset: 276},
						name: "Array",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 44, offset: 284},
						name: "Object",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 53, offset: 293},
						name: "String",
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 13, col: 1, offset: 301},
			expr: &actionExpr{
				pos: position{line: 13, col: 9, offset: 309},
				run: (*parser).callonNull1,
				expr: &ruleRefExpr{
					pos:  position{line: 13, col: 9, offset: 309},
					name: "NULL",
				},
			},
		},
		{
			name: "Boolean",
			pos:  position{line: 15, col: 1, offset: 336},
			expr: &actionExpr{
				pos: position{line: 15, col: 12, offset: 347},
				run: (*parser).callonBoolean1,
				expr: &labeledExpr{
					pos:   position{line: 15, col: 12, offset: 347},
					label: "v1",
					expr: &choiceExpr{
						pos: position{line: 15, col: 16, offset: 351},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 15, col: 16, offset: 351},
								name: "TRUE",
							},
							&ruleRefExpr{
								pos:  position{line: 15, col: 23, offset: 358},
								name: "FALSE",
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 17, col: 1, offset: 391},
			expr: &actionExpr{
				pos: position{line: 17, col: 11, offset: 401},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 17, col: 11, offset: 401},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 17, col: 11, offset: 401},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 15, offset: 405},
							label: "v1",
							expr: &zeroOrMoreExpr{
								pos: position{line: 17, col: 18, offset: 408},
								expr: &seqExpr{
									pos: position{line: 17, col: 19, offset: 409},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 17, col: 19, offset: 409},
											expr: &litMatcher{
												pos:        position{line: 17, col: 20, offset: 410},
												val:        "\"",
												ignoreCase: false,
												want:       "\"\\\"\"",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 17, col: 24, offset: 414},
											name: "Character",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 17, col: 36, offset: 426},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&ruleRefExpr{
							pos:  position{line: 17, col: 40, offset: 430},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 19, col: 1, offset: 461},
			expr: &actionExpr{
				pos: position{line: 19, col: 15, offset: 475},
				run: (*parser).callonExpression1,
				expr: &seqExpr{
					pos: position{line: 19, col: 15, offset: 475},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 19, col: 15, offset: 475},
							label: "v1",
							expr: &ruleRefExpr{
								pos:  position{line: 19, col: 18, offset: 478},
								name: "Selector",
							},
						},
						&labeledExpr{
							pos:   position{line: 19, col: 27, offset: 487},
							label: "v2",
							expr: &zeroOrMoreExpr{
								pos: position{line: 19, col: 30, offset: 490},
								expr: &seqExpr{
									pos: position{line: 19, col: 31, offset: 491},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 19, col: 31, offset: 491},
											name: "Op",
										},
										&ruleRefExpr{
											pos:  position{line: 19, col: 34, offset: 494},
											name: "Selector",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Selector",
			pos:  position{line: 21, col: 1, offset: 541},
			expr: &actionExpr{
				pos: position{line: 21, col: 13, offset: 553},
				run: (*parser).callonSelector1,
				expr: &seqExpr{
					pos: position{line: 21, col: 13, offset: 553},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 21, col: 13, offset: 553},
							label: "v1",
							expr: &zeroOrOneExpr{
								pos: position{line: 21, col: 16, offset: 556},
								expr: &ruleRefExpr{
									pos:  position{line: 21, col: 16, offset: 556},
									name: "NOT",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 21, col: 21, offset: 561},
							label: "v2",
							expr: &choiceExpr{
								pos: position{line: 21, col: 25, offset: 565},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 21, col: 25, offset: 565},
										name: "Parens",
									},
									&ruleRefExpr{
										pos:  position{line: 21, col: 34, offset: 574},
										name: "Value",
									},
									&ruleRefExpr{
										pos:  position{line: 21, col: 42, offset: 582},
										name: "Identifier",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 21, col: 54, offset: 594},
							label: "v3",
							expr: &zeroOrMoreExpr{
								pos: position{line: 21, col: 57, offset: 597},
								expr: &ruleRefExpr{
									pos:  position{line: 21, col: 57, offset: 597},
									name: "DotLookup",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Parens",
			pos:  position{line: 23, col: 1, offset: 646},
			expr: &actionExpr{
				pos: position{line: 23, col: 11, offset: 656},
				run: (*parser).callonParens1,
				expr: &seqExpr{
					pos: position{line: 23, col: 11, offset: 656},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 23, col: 11, offset: 656},
							name: "LPAREN",
						},
						&labeledExpr{
							pos:   position{line: 23, col: 18, offset: 663},
							label: "v1",
							expr: &ruleRefExpr{
								pos:  position{line: 23, col: 21, offset: 666},
								name: "Expression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 23, col: 32, offset: 677},
							name: "RPAREN",
						},
					},
				},
			},
		},
		{
			name: "DotLookup",
			pos:  position{line: 25, col: 1, offset: 712},
			expr: &actionExpr{
				pos: position{line: 25, col: 14, offset: 725},
				run: (*parser).callonDotLookup1,
				expr: &seqExpr{
					pos: position{line: 25, col: 14, offset: 725},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 25, col: 14, offset: 725},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 25, col: 18, offset: 729},
							label: "v1",
							expr: &ruleRefExpr{
								pos:  position{line: 25, col: 21, offset: 732},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Op",
			pos:  position{line: 27, col: 1, offset: 774},
			expr: &actionExpr{
				pos: position{line: 27, col: 7, offset: 780},
				run: (*parser).callonOp1,
				expr: &labeledExpr{
					pos:   position{line: 27, col: 7, offset: 780},
					label: "v1",
					expr: &choiceExpr{
						pos: position{line: 27, col: 11, offset: 784},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 27, col: 11, offset: 784},
								name: "MINUS",
							},
							&ruleRefExpr{
								pos:  position{line: 27, col: 19, offset: 792},
								name: "PLUS",
							},
							&ruleRefExpr{
								pos:  position{line: 27, col: 26, offset: 799},
								name: "MUL",
							},
							&ruleRefExpr{
								pos:  position{line: 27, col: 32, offset: 805},
								name: "DIVIDE",
							},
							&ruleRefExpr{
								pos:  position{line: 27, col: 41, offset: 814},
								name: "AND",
							},
							&ruleRefExpr{
								pos:  position{line: 27, col: 47, offset: 820},
								name: "OR",
							},
							&ruleRefExpr{
								pos:  position{line: 27, col: 52, offset: 825},
								name: "MERGE",
							},
						},
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 29, col: 1, offset: 857},
			expr: &actionExpr{
				pos: position{line: 29, col: 10, offset: 866},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 29, col: 10, offset: 866},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 29, col: 10, offset: 866},
							name: "LBRACKET",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 19, offset: 875},
							label: "v1",
							expr: &zeroOrOneExpr{
								pos: position{line: 29, col: 22, offset: 878},
								expr: &ruleRefExpr{
									pos:  position{line: 29, col: 22, offset: 878},
									name: "Expression",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 29, col: 34, offset: 890},
							label: "v2",
							expr: &zeroOrMoreExpr{
								pos: position{line: 29, col: 37, offset: 893},
								expr: &seqExpr{
									pos: position{line: 29, col: 38, offset: 894},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 29, col: 38, offset: 894},
											name: "COMMA",
										},
										&ruleRefExpr{
											pos:  position{line: 29, col: 44, offset: 900},
											name: "Expression",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 29, col: 57, offset: 913},
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 57, offset: 913},
								name: "COMMA",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 64, offset: 920},
							name: "RBRACKET",
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 31, col: 1, offset: 960},
			expr: &actionExpr{
				pos: position{line: 31, col: 15, offset: 974},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 31, col: 15, offset: 974},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 31, col: 15, offset: 974},
							name: "IdentStart",
						},
						&zeroOrMoreExpr{
							pos: position{line: 31, col: 26, offset: 985},
							expr: &ruleRefExpr{
								pos:  position{line: 31, col: 26, offset: 985},
								name: "IdentCont",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 31, col: 37, offset: 996},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "IdentStart",
			pos:  position{line: 32, col: 1, offset: 1027},
			expr: &charClassMatcher{
				pos:        position{line: 32, col: 15, offset: 1041},
				val:        "[a-zA-Z_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "IdentCont",
			pos:  position{line: 33, col: 1, offset: 1051},
			expr: &choiceExpr{
				pos: position{line: 33, col: 14, offset: 1064},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 33, col: 14, offset: 1064},
						name: "IdentStart",
					},
					&ruleRefExpr{
						pos:  position{line: 33, col: 27, offset: 1077},
						name: "Digit",
					},
				},
			},
		},
		{
			name: "Character",
			pos:  position{line: 35, col: 1, offset: 1084},
			expr: &choiceExpr{
				pos: position{line: 35, col: 14, offset: 1097},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 35, col: 14, offset: 1097},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 35, col: 14, offset: 1097},
								val:        "\\",
								ignoreCase: false,
								want:       "\"\\\\\"",
							},
							&litMatcher{
								pos:        position{line: 35, col: 19, offset: 1102},
								val:        "u",
								ignoreCase: false,
								want:       "\"u\"",
							},
							&ruleRefExpr{
								pos:  position{line: 35, col: 23, offset: 1106},
								name: "Hex",
							},
							&ruleRefExpr{
								pos:  position{line: 35, col: 27, offset: 1110},
								name: "Hex",
							},
							&ruleRefExpr{
								pos:  position{line: 35, col: 31, offset: 1114},
								name: "Hex",
							},
							&ruleRefExpr{
								pos:  position{line: 35, col: 35, offset: 1118},
								name: "Hex",
							},
						},
					},
					&seqExpr{
						pos: position{line: 36, col: 5, offset: 1128},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 36, col: 5, offset: 1128},
								val:        "\\",
								ignoreCase: false,
								want:       "\"\\\\\"",
							},
							&charClassMatcher{
								pos:        position{line: 36, col: 10, offset: 1133},
								val:        "[bfnrt'\"\\\\]",
								chars:      []rune{'b', 'f', 'n', 'r', 't', '\'', '"', '\\'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
					&actionExpr{
						pos: position{line: 37, col: 5, offset: 1151},
						run: (*parser).callonCharacter12,
						expr: &charClassMatcher{
							pos:        position{line: 37, col: 5, offset: 1151},
							val:        "[\\u0020-\\u10FFFF]",
							chars:      []rune{'F', 'F'},
							ranges:     []rune{' ', 'ჿ'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Hex",
			pos:  position{line: 39, col: 1, offset: 1191},
			expr: &choiceExpr{
				pos: position{line: 39, col: 8, offset: 1198},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 39, col: 8, offset: 1198},
						name: "Digit",
					},
					&charClassMatcher{
						pos:        position{line: 39, col: 16, offset: 1206},
						val:        "[a-fA-F]",
						ranges:     []rune{'a', 'f', 'A', 'F'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Digit",
			pos:  position{line: 40, col: 1, offset: 1215},
			expr: &choiceExpr{
				pos: position{line: 40, col: 10, offset: 1224},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 40, col: 10, offset: 1224},
						val:        "0",
						ignoreCase: false,
						want:       "\"0\"",
					},
					&ruleRefExpr{
						pos:  position{line: 40, col: 16, offset: 1230},
						name: "OneNine",
					},
				},
			},
		},
		{
			name: "OneNine",
			pos:  position{line: 41, col: 1, offset: 1238},
			expr: &charClassMatcher{
				pos:        position{line: 41, col: 12, offset: 1249},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Number",
			pos:  position{line: 43, col: 1, offset: 1256},
			expr: &actionExpr{
				pos: position{line: 43, col: 11, offset: 1266},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 43, col: 11, offset: 1266},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 43, col: 11, offset: 1266},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 43, col: 19, offset: 1274},
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 19, offset: 1274},
								name: "Fraction",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 43, col: 29, offset: 1284},
							expr: &ruleRefExpr{
								pos:  position{line: 43, col: 29, offset: 1284},
								name: "Exponent",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 43, col: 39, offset: 1294},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 44, col: 1, offset: 1320},
			expr: &choiceExpr{
				pos: position{line: 44, col: 12, offset: 1331},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 44, col: 12, offset: 1331},
						name: "Digit",
					},
					&seqExpr{
						pos: position{line: 44, col: 20, offset: 1339},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 44, col: 20, offset: 1339},
								name: "OneNine",
							},
							&oneOrMoreExpr{
								pos: position{line: 44, col: 28, offset: 1347},
								expr: &ruleRefExpr{
									pos:  position{line: 44, col: 28, offset: 1347},
									name: "Digit",
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 44, col: 37, offset: 1356},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 44, col: 37, offset: 1356},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
							&ruleRefExpr{
								pos:  position{line: 44, col: 41, offset: 1360},
								name: "Digit",
							},
						},
					},
					&seqExpr{
						pos: position{line: 44, col: 49, offset: 1368},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 44, col: 49, offset: 1368},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
							&ruleRefExpr{
								pos:  position{line: 44, col: 53, offset: 1372},
								name: "OneNine",
							},
							&oneOrMoreExpr{
								pos: position{line: 44, col: 61, offset: 1380},
								expr: &ruleRefExpr{
									pos:  position{line: 44, col: 61, offset: 1380},
									name: "Digit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Fraction",
			pos:  position{line: 45, col: 1, offset: 1387},
			expr: &seqExpr{
				pos: position{line: 45, col: 13, offset: 1399},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 45, col: 13, offset: 1399},
						val:        ".",
						ignoreCase: false,
						want:       "\".\"",
					},
					&oneOrMoreExpr{
						pos: position{line: 45, col: 17, offset: 1403},
						expr: &ruleRefExpr{
							pos:  position{line: 45, col: 17, offset: 1403},
							name: "Digit",
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 46, col: 1, offset: 1410},
			expr: &seqExpr{
				pos: position{line: 46, col: 13, offset: 1422},
				exprs: []interface{}{
					&charClassMatcher{
						pos:        position{line: 46, col: 13, offset: 1422},
						val:        "[Ee]",
						chars:      []rune{'E', 'e'},
						ignoreCase: false,
						inverted:   false,
					},
					&zeroOrOneExpr{
						pos: position{line: 46, col: 18, offset: 1427},
						expr: &ruleRefExpr{
							pos:  position{line: 46, col: 18, offset: 1427},
							name: "Sign",
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 46, col: 24, offset: 1433},
						expr: &ruleRefExpr{
							pos:  position{line: 46, col: 24, offset: 1433},
							name: "Digit",
						},
					},
				},
			},
		},
		{
			name: "Sign",
			pos:  position{line: 47, col: 1, offset: 1440},
			expr: &charClassMatcher{
				pos:        position{line: 47, col: 9, offset: 1448},
				val:        "[-+]",
				chars:      []rune{'-', '+'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "__",
			pos:  position{line: 49, col: 1, offset: 1454},
			expr: &zeroOrMoreExpr{
				pos: position{line: 49, col: 7, offset: 1460},
				expr: &choiceExpr{
					pos: position{line: 49, col: 8, offset: 1461},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 49, col: 8, offset: 1461},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 49, col: 12, offset: 1465},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 50, col: 1, offset: 1475},
			expr: &choiceExpr{
				pos: position{line: 50, col: 6, offset: 1480},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 50, col: 6, offset: 1480},
						val:        " ",
						ignoreCase: false,
						want:       "\" \"",
					},
					&litMatcher{
						pos:        position{line: 50, col: 12, offset: 1486},
						val:        "\t",
						ignoreCase: false,
						want:       "\"\\t\"",
					},
					&ruleRefExpr{
						pos:  position{line: 50, col: 19, offset: 1493},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 51, col: 1, offset: 1497},
			expr: &seqExpr{
				pos: position{line: 51, col: 12, offset: 1508},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 51, col: 12, offset: 1508},
						val:        "//",
						ignoreCase: false,
						want:       "\"//\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 51, col: 17, offset: 1513},
						expr: &seqExpr{
							pos: position{line: 51, col: 18, offset: 1514},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 51, col: 18, offset: 1514},
									expr: &ruleRefExpr{
										pos:  position{line: 51, col: 19, offset: 1515},
										name: "EOL",
									},
								},
								&anyMatcher{
									line: 51, col: 23, offset: 1519,
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 51, col: 27, offset: 1523},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "Quote",
			pos:  position{line: 52, col: 1, offset: 1527},
			expr: &litMatcher{
				pos:        position{line: 52, col: 10, offset: 1536},
				val:        "\"",
				ignoreCase: false,
				want:       "\"\\\"\"",
			},
		},
		{
			name: "EOL",
			pos:  position{line: 53, col: 1, offset: 1540},
			expr: &choiceExpr{
				pos: position{line: 53, col: 8, offset: 1547},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 53, col: 8, offset: 1547},
						val:        "\r\n",
						ignoreCase: false,
						want:       "\"\\r\\n\"",
					},
					&litMatcher{
						pos:        position{line: 53, col: 17, offset: 1556},
						val:        "\n",
						ignoreCase: false,
						want:       "\"\\n\"",
					},
					&litMatcher{
						pos:        position{line: 53, col: 24, offset: 1563},
						val:        "\r",
						ignoreCase: false,
						want:       "\"\\r\"",
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 54, col: 1, offset: 1568},
			expr: &notExpr{
				pos: position{line: 54, col: 8, offset: 1575},
				expr: &anyMatcher{
					line: 54, col: 9, offset: 1576,
				},
			},
		},
		{
			name: "NULL",
			pos:  position{line: 57, col: 1, offset: 1629},
			expr: &actionExpr{
				pos: position{line: 57, col: 9, offset: 1637},
				run: (*parser).callonNULL1,
				expr: &seqExpr{
					pos: position{line: 57, col: 9, offset: 1637},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 57, col: 9, offset: 1637},
							val:        "null",
							ignoreCase: false,
							want:       "\"null\"",
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 16, offset: 1644},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "TRUE",
			pos:  position{line: 58, col: 1, offset: 1675},
			expr: &actionExpr{
				pos: position{line: 58, col: 9, offset: 1683},
				run: (*parser).callonTRUE1,
				expr: &seqExpr{
					pos: position{line: 58, col: 9, offset: 1683},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 58, col: 9, offset: 1683},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
						&ruleRefExpr{
							pos:  position{line: 58, col: 16, offset: 1690},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "FALSE",
			pos:  position{line: 59, col: 1, offset: 1721},
			expr: &actionExpr{
				pos: position{line: 59, col: 10, offset: 1730},
				run: (*parser).callonFALSE1,
				expr: &seqExpr{
					pos: position{line: 59, col: 10, offset: 1730},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 59, col: 10, offset: 1730},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
						&ruleRefExpr{
							pos:  position{line: 59, col: 18, offset: 1738},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "NOT",
			pos:  position{line: 60, col: 1, offset: 1769},
			expr: &actionExpr{
				pos: position{line: 60, col: 8, offset: 1776},
				run: (*parser).callonNOT1,
				expr: &seqExpr{
					pos: position{line: 60, col: 8, offset: 1776},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 60, col: 8, offset: 1776},
							val:        "!",
							ignoreCase: false,
							want:       "\"!\"",
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 12, offset: 1780},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "FOR",
			pos:  position{line: 61, col: 1, offset: 1811},
			expr: &actionExpr{
				pos: position{line: 61, col: 8, offset: 1818},
				run: (*parser).callonFOR1,
				expr: &seqExpr{
					pos: position{line: 61, col: 8, offset: 1818},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 61, col: 8, offset: 1818},
							val:        "for",
							ignoreCase: false,
							want:       "\"for\"",
						},
						&ruleRefExpr{
							pos:  position{line: 61, col: 14, offset: 1824},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "COMMA",
			pos:  position{line: 62, col: 1, offset: 1855},
			expr: &actionExpr{
				pos: position{line: 62, col: 10, offset: 1864},
				run: (*parser).callonCOMMA1,
				expr: &seqExpr{
					pos: position{line: 62, col: 10, offset: 1864},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 62, col: 10, offset: 1864},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 62, col: 14, offset: 1868},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "LPAREN",
			pos:  position{line: 63, col: 1, offset: 1899},
			expr: &actionExpr{
				pos: position{line: 63, col: 11, offset: 1909},
				run: (*parser).callonLPAREN1,
				expr: &seqExpr{
					pos: position{line: 63, col: 11, offset: 1909},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 63, col: 11, offset: 1909},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 15, offset: 1913},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "RPAREN",
			pos:  position{line: 64, col: 1, offset: 1944},
			expr: &actionExpr{
				pos: position{line: 64, col: 11, offset: 1954},
				run: (*parser).callonRPAREN1,
				expr: &seqExpr{
					pos: position{line: 64, col: 11, offset: 1954},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 64, col: 11, offset: 1954},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
						&ruleRefExpr{
							pos:  position{line: 64, col: 15, offset: 1958},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "LBRACE",
			pos:  position{line: 65, col: 1, offset: 1989},
			expr: &actionExpr{
				pos: position{line: 65, col: 11, offset: 1999},
				run: (*parser).callonLBRACE1,
				expr: &seqExpr{
					pos: position{line: 65, col: 11, offset: 1999},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 65, col: 11, offset: 1999},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 65, col: 15, offset: 2003},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "RBRACE",
			pos:  position{line: 66, col: 1, offset: 2034},
			expr: &actionExpr{
				pos: position{line: 66, col: 11, offset: 2044},
				run: (*parser).callonRBRACE1,
				expr: &seqExpr{
					pos: position{line: 66, col: 11, offset: 2044},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 66, col: 11, offset: 2044},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
						&ruleRefExpr{
							pos:  position{line: 66, col: 15, offset: 2048},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "LBRACKET",
			pos:  position{line: 67, col: 1, offset: 2079},
			expr: &actionExpr{
				pos: position{line: 67, col: 13, offset: 2091},
				run: (*parser).callonLBRACKET1,
				expr: &seqExpr{
					pos: position{line: 67, col: 13, offset: 2091},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 67, col: 13, offset: 2091},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 67, col: 17, offset: 2095},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "RBRACKET",
			pos:  position{line: 68, col: 1, offset: 2126},
			expr: &actionExpr{
				pos: position{line: 68, col: 13, offset: 2138},
				run: (*parser).callonRBRACKET1,
				expr: &seqExpr{
					pos: position{line: 68, col: 13, offset: 2138},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 68, col: 13, offset: 2138},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 17, offset: 2142},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "MINUS",
			pos:  position{line: 69, col: 1, offset: 2173},
			expr: &actionExpr{
				pos: position{line: 69, col: 10, offset: 2182},
				run: (*parser).callonMINUS1,
				expr: &seqExpr{
					pos: position{line: 69, col: 10, offset: 2182},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 69, col: 10, offset: 2182},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
						&ruleRefExpr{
							pos:  position{line: 69, col: 14, offset: 2186},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "MUL",
			pos:  position{line: 70, col: 1, offset: 2217},
			expr: &actionExpr{
				pos: position{line: 70, col: 8, offset: 2224},
				run: (*parser).callonMUL1,
				expr: &seqExpr{
					pos: position{line: 70, col: 8, offset: 2224},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 70, col: 8, offset: 2224},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 12, offset: 2228},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "PLUS",
			pos:  position{line: 71, col: 1, offset: 2259},
			expr: &actionExpr{
				pos: position{line: 71, col: 9, offset: 2267},
				run: (*parser).callonPLUS1,
				expr: &seqExpr{
					pos: position{line: 71, col: 9, offset: 2267},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 71, col: 9, offset: 2267},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
						&ruleRefExpr{
							pos:  position{line: 71, col: 13, offset: 2271},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "DIVIDE",
			pos:  position{line: 72, col: 1, offset: 2302},
			expr: &actionExpr{
				pos: position{line: 72, col: 11, offset: 2312},
				run: (*parser).callonDIVIDE1,
				expr: &seqExpr{
					pos: position{line: 72, col: 11, offset: 2312},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 72, col: 11, offset: 2312},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
						&ruleRefExpr{
							pos:  position{line: 72, col: 15, offset: 2316},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "MERGE",
			pos:  position{line: 73, col: 1, offset: 2347},
			expr: &actionExpr{
				pos: position{line: 73, col: 10, offset: 2356},
				run: (*parser).callonMERGE1,
				expr: &seqExpr{
					pos: position{line: 73, col: 10, offset: 2356},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 73, col: 10, offset: 2356},
							val:        "&",
							ignoreCase: false,
							want:       "\"&\"",
						},
						&ruleRefExpr{
							pos:  position{line: 73, col: 14, offset: 2360},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "AND",
			pos:  position{line: 74, col: 1, offset: 2391},
			expr: &actionExpr{
				pos: position{line: 74, col: 8, offset: 2398},
				run: (*parser).callonAND1,
				expr: &seqExpr{
					pos: position{line: 74, col: 8, offset: 2398},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 74, col: 8, offset: 2398},
							val:        "&&",
							ignoreCase: false,
							want:       "\"&&\"",
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 13, offset: 2403},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "OR",
			pos:  position{line: 75, col: 1, offset: 2434},
			expr: &actionExpr{
				pos: position{line: 75, col: 7, offset: 2440},
				run: (*parser).callonOR1,
				expr: &seqExpr{
					pos: position{line: 75, col: 7, offset: 2440},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 75, col: 7, offset: 2440},
							val:        "||",
							ignoreCase: false,
							want:       "\"||\"",
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 12, offset: 2445},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "COLON",
			pos:  position{line: 76, col: 1, offset: 2476},
			expr: &actionExpr{
				pos: position{line: 76, col: 10, offset: 2485},
				run: (*parser).callonCOLON1,
				expr: &seqExpr{
					pos: position{line: 76, col: 10, offset: 2485},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 76, col: 10, offset: 2485},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 14, offset: 2489},
							name: "__",
						},
					},
				},
			},
		},
	},
}

func (c *current) onInput1(v1 interface{}) (interface{}, error) {
	return toInput(v1, c)
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["v1"])
}

func (c *current) onObject1(v1 interface{}) (interface{}, error) {
	return toObject(v1, c)
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["v1"])
}

func (c *current) onField1(v1, v2 interface{}) (interface{}, error) {
	return toField(v1, v2, c)
}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["v1"], stack["v2"])
}

func (c *current) onNull1() (interface{}, error) {
	return toNull(c)
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onBoolean1(v1 interface{}) (interface{}, error) {
	return toBool(v1, c)
}

func (p *parser) callonBoolean1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean1(stack["v1"])
}

func (c *current) onString1(v1 interface{}) (interface{}, error) {
	return toString(v1, c)
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1(stack["v1"])
}

func (c *current) onExpression1(v1, v2 interface{}) (interface{}, error) {
	return toExpression(v1, v2, c)
}

func (p *parser) callonExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpression1(stack["v1"], stack["v2"])
}

func (c *current) onSelector1(v1, v2, v3 interface{}) (interface{}, error) {
	return toSelector(v1, v2, v3, c)
}

func (p *parser) callonSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelector1(stack["v1"], stack["v2"], stack["v3"])
}

func (c *current) onParens1(v1 interface{}) (interface{}, error) {
	return toParens(v1, c)
}

func (p *parser) callonParens1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParens1(stack["v1"])
}

func (c *current) onDotLookup1(v1 interface{}) (interface{}, error) {
	return toDotLookup(v1, c)
}

func (p *parser) callonDotLookup1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDotLookup1(stack["v1"])
}

func (c *current) onOp1(v1 interface{}) (interface{}, error) {
	return newOp(v1, c)
}

func (p *parser) callonOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOp1(stack["v1"])
}

func (c *current) onArray1(v1, v2 interface{}) (interface{}, error) {
	return toArray(v1, v2, c)
}

func (p *parser) callonArray1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray1(stack["v1"], stack["v2"])
}

func (c *current) onIdentifier1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onCharacter12() (interface{}, error) {
	return toChar(c)
}

func (p *parser) callonCharacter12() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharacter12()
}

func (c *current) onNumber1() (interface{}, error) {
	return toNumber(c)
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onNULL1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonNULL1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNULL1()
}

func (c *current) onTRUE1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonTRUE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTRUE1()
}

func (c *current) onFALSE1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonFALSE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFALSE1()
}

func (c *current) onNOT1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonNOT1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNOT1()
}

func (c *current) onFOR1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonFOR1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFOR1()
}

func (c *current) onCOMMA1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonCOMMA1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOMMA1()
}

func (c *current) onLPAREN1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonLPAREN1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLPAREN1()
}

func (c *current) onRPAREN1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonRPAREN1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRPAREN1()
}

func (c *current) onLBRACE1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonLBRACE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLBRACE1()
}

func (c *current) onRBRACE1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonRBRACE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRBRACE1()
}

func (c *current) onLBRACKET1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonLBRACKET1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLBRACKET1()
}

func (c *current) onRBRACKET1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonRBRACKET1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRBRACKET1()
}

func (c *current) onMINUS1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonMINUS1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMINUS1()
}

func (c *current) onMUL1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonMUL1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMUL1()
}

func (c *current) onPLUS1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonPLUS1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPLUS1()
}

func (c *current) onDIVIDE1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonDIVIDE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDIVIDE1()
}

func (c *current) onMERGE1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonMERGE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMERGE1()
}

func (c *current) onAND1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonAND1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAND1()
}

func (c *current) onOR1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonOR1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOR1()
}

func (c *current) onCOLON1() (interface{}, error) {
	return currentString(c)
}

func (p *parser) callonCOLON1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCOLON1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
